export enum EventType {
  GEOPOLITICAL = 'GEOPOLITICAL',
  LOGISTICS = 'LOGISTICS',
  INFRASTRUCTURE = 'INFRASTRUCTURE',
  MARKET = 'MARKET',
  NATURAL = 'NATURAL',
  REGULATORY = 'REGULATORY',
  OTHER = 'OTHER',
}
