export enum ScenarioState {
  DRAFT = 'DRAFT',
  READY = 'READY',
  EVALUATING = 'EVALUATING',
  EVALUATED = 'EVALUATED',
  RECOMMENDED = 'RECOMMENDED',
  DECIDED = 'DECIDED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}
